version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # รหัส root
      MYSQL_DATABASE: mydatabase          # ชื่อ DB ที่ต้องการสร้าง
      MYSQL_USER: myuser                  # user ใหม่
      MYSQL_PASSWORD: mypassword          # password ของ user
    ports:
      - "6033:3306"  # เข้าถึงผ่าน localhost:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
