version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    env_file:
      - .env.example
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go-redis-app
  #   env_file:
  #     - .env.example
  #   depends_on:
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   command: ["go", "run", "./cmd/main.go"]

volumes:
  redis_data:
